name: bang
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  url_launcher: <6.2.2
  audioplayers: <5.2.1
  path_provider: ^2.1.1
  provider: ^6.1.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  wakelock_plus: ^1.4.0
  http: ^1.1.2
  ota_update: ^7.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/data/
  fonts:
    - family: NotoNaskh
      fonts:
        - asset: assets/fonts/noto.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/m_icon.png"
  remove_alpha_ios: true
