name: bang
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  url_launcher: <6.1.12
  audioplayers: <5.2.1
  path_provider: ^2.1.1
  provider: ^6.1.2
  flutter_local_notifications: ^17.0.0  # ← نوێ
  timezone: ^0.9.0  # ← نوێ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: notonaskh
      fonts:
        - asset: assets/fonts/noto.ttf

flutter_launcher_icons:  # ← ناوی دروست
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true